### ISSUE TITLE
Bug: problem with the sliders

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#496] opened 2019-11-01 13:50 UTC
I prefer to add a gif directly, as it is quite complicated to explain this bug:
Note that it is exactly the same problem no matter the type of filter (transparency, time slider, etc)
 
![bug_filters](https://user-images.githubusercontent.com/25179050/68029157-ee134b00-fcb6-11e9-8388-da7cac6426f4.gif)

**Comment by antobenve** [comment] 2019-11-01 13:53
Thanks @MarionPlanque , we are aware of it and it will be fixed soon. However, tt is a good idea to have it in GitHub as well so that users see that the bug is being addressed.

**Comment by fxi** [comment] 2019-11-04 14:50
Ready to be tested in 1.6.25

**Comment by antobenve** [comment] 2019-11-04 14:55
The issue is solved in locally available MapX. I'll close the issue as soon as it will be available online.

**Comment by antobenve** [comment] 2019-11-05 16:35
Unfortunately I can't close the issue because this problem also concerns the sliders in custom code views that are located in the legend environment. 
[View to be tested](https://app.mapx.org?project=MX-XVK-HPH-OGN-HVE-GGN&viewsOpen=MX-6BI2W-R1HNH-THYSG
)

**Comment by antobenve** [comment] 2019-11-06 16:43
It seems fine to me know. I'm closing the issue.

**Closed by antobenve** 2019-11-06 16:43 UTC
Labels: bug, done, priority 1
