### ISSUE TITLE
Bug abstract metadata for a view

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#438] opened 2019-05-17 13:24 UTC
There is a bug in the abstract of the metadata window in the following view: Zoning and Coding of Colombia Hydrographic and Hydrogeological Units. Scale 1:500.000. Year: 2013
(here is the link: https://app.mapx.org?project=MX-SXE-0C1-TTW-KC8-VP4&views=MX-3NUDO-I1VN2-HUVJA )

The abstract exceeds the frame of the metadata window, as shown below. I couldn't see this problem in any other view nor any bug in the metadata.
![image](https://user-images.githubusercontent.com/25179050/57930831-3ed4ea00-78b7-11e9-9b5e-57a38bffd359.png)

**Comment by antobenve** [comment] 2019-05-17 14:25
Thanks Marion, 
The problem is related to long urls which are present in the abstract of the source. Same problem can also be triggered in the abstract of the views if long urls are there. The problem should be related to the way the browser handles these situations. For instance Firefox breaks the url apart where it is needed while Chrome only does it when it finds a "-"
The use of hyperlinks helps not to trigger the issue. 
![image](https://user-images.githubusercontent.com/30286565/57932913-3af79680-78bc-11e9-8f13-efc34d9d18e0.png)

**Comment by MarionPlanque** [comment] 2019-05-17 14:50
Thanks for your response @antobenve , that makes perfect sense indeed
However, my only concern is that it's actually not possible to add hyperlinks in the metadata, only in the text (title/abstract) of the view itself (or at least it wasn't possible last time I tried). So, we are constraints by the length of the urls contained in the abstract in the metadata window...

**Comment by antobenve** [comment] 2019-05-17 15:18
@MarionPlanque , I tested online and I confirm that this is possible in source metadata too. I think this is related to the upgrade of the metadata visualizer, which is capable to interpret html synthax since then.

**Comment by MarionPlanque** [comment] 2019-05-17 15:20
Oh great! It's good news, many thanks

**Comment by antobenve** [comment] 2019-05-17 15:27
Thanks for your report @MarionPlanque . As an issue is already open on this (#350 ), can you please close this one?

**Closed** 2019-05-17 15:29 UTC
