### ISSUE TITLE
Revision of the view management system in story maps

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#107] opened 2017-10-09 08:14 UTC
### Expected Behavior

The management of views in story maps must be changed to not overload a country with shared views.

### Current Behavior

The management of views in story maps involving several countries (available in World) is not good. It is based on the sharing of views from countries to World and therefore there are far too many views in World which serve only to the story maps.

### Possible Solution

In "Views to activate", all views accessible by the user must be listed and in _selectize_, views must be grouped by country.

**Comment by MarionPlanque** [comment] 2017-11-01 09:28
Suggestion of feature: 
![background](https://user-images.githubusercontent.com/25179050/32268420-4d322f5a-beef-11e7-83ba-111698d85c01.png)

**Comment by thomaspiller** [comment] 2017-12-21 16:17
In views to activate, all views are now listed in the drop-down list. I made some tests and everything seems fine. Can I close this issue?

**Comment by MarionPlanque** [comment] 2017-12-21 16:23
Not yet I think: all this views are listed in the menu indeed (the problem is solved), but as all of them are listed, it can be very difficult to find one if the name of the view is not already known. 
I think we should now think of a way to organize the way to select the views in the drop-down list.
But maybe we can close this bug and open an "improvement" topic?

**Comment by antobenve** [comment] 2018-08-17 15:34
@MarionPlanque , is this issue solved or the last comment is about something that must still be addressed?

**Comment by thomaspiller** [comment] 2019-01-11 11:16
@MarionPlanque, is this issue solved?

**Comment by MarionPlanque** [comment] 2019-01-11 11:57
Not really: we switched to another system, but now the problem is that for each view proposed in the list of views, it is not indicated which project the view is coming from
It's a major problem because view names don't contain indication about the project
_Example_:
- "Protected areas (CNIGS - 2017)" ------ (from the Haiti project)
- "Protected areas IUCN" ------- (from the world project)


**Suggestion**: the views availablke in the story map should mention in their label the project they come from
_Example_: "World - Protected areas"; "UN Environment Haiti - protected areas"

**Closed** 2019-09-13 14:37 UTC
Labels: Priority 2, Wait feedback, feature request
