### ISSUE TITLE
Story map editor does not display properly in Edge - Bug

### ISSUE THREAD

**Issue by davidedwardjensen** [unep-grid/map-x-mgl#210] opened 2018-02-28 11:19 UTC
The story map edit does not display properly using Edge in Windows 10.

![image](https://user-images.githubusercontent.com/17933528/36784983-990b4412-1c81-11e8-956a-be8ae6346800.png)

[edit] Formating :/

**Comment by fxi** [comment] 2018-03-05 16:31
Issue not reproducible using Microsoft Edge 41.16299.15.0 (on /test, but the main / share the same style code)

![image](https://user-images.githubusercontent.com/1196833/36986553-63895b90-209a-11e8-928c-ef73b0c51ced.png)

**Comment by thomaspiller** [comment] 2019-05-27 13:20
Since no feedback has been provided for over a year and the story map engine has much evolved since then, I close this issue. If the problem is encountered again, please re-open this issue.

**Closed by thomaspiller** 2019-05-27 13:20 UTC
Labels: Wait feedback
