### ISSUE TITLE
SDK : react example is not in sync with with the view list and some issue

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#548] opened 2020-05-05 08:44 UTC
@trepmag : Minor issue. The react example does trigger the MapX list of enabled views, but the use of MapX views list does not change back the state of the component. Maybe this could be done using a listener, on "view_added" event, which returns an object with view id : `{idView: "MX-0NOMK-IO4KS-L0KOD", time: 1588667935256}`

Another issue not reported in my review : we use jshint to check for potential errors and formatting issues. See our [.jshintrc](https://github.com/unep-grid/map-x-mgl/blob/master/.jshintrc). It could be great to stick to those rules to avoid big mismatch in the code style.

**Comment by trepmag** [comment] 2020-05-12 09:43
Hello, with trepmag/map-x-mgl@5e5f2f2 the component that build the triggering links now use `view_added` to change its state. Not that `view_closed` is called but not triggered at mapx level...

Regarding jshint: well noted! Btw, it appears that it doesn't copes with JSX well which is what is used in example 4. It would requires to switch to eslint...

**Comment by fxi** [comment] 2020-05-12 11:19
I personally don't like jsx and I will probably never use it. Writing degraded XML by hand, inside js does not make any sense to me. 

I wrote a package, @fxi/el, to write elements very easily. It's widely used in MapX. It's fast and very simple. I always choose simplicity and speed over complexity. 

JSHint was faster at the time and very easy to use.  I we start using eslint, we have to make sure that the configuration match as much as possible our `.jshintrc`

**Comment by trepmag** [comment] 2020-05-12 11:39
Outside of personal taste the example is to showcase the usage of the SDK using React and thus follow React usage... Does it make sense?

**Comment by fxi** [comment] 2020-05-12 11:46
I guess so, yes. It seems rather uncommon to use anything else than jsx with React. As it's an example, we can just put this aside until we switch to eslint. We can also have a local eslintrc for this case.

**Comment by trepmag** [comment] 2020-06-08 06:57
@fxi as you can see listening on view_added can quiet cumbersome as we must build the link btw the open and the opened event...

Somehow, it would much convenient to be able to write something as follow:
```
mapx.ask('open_view', {idView: 'abc'}).then((status, view) => {

  console.log(view.idView);
  // output 'abc'

  switch(status) {
    case 'started':
      // do something...
      break;
    case 'finished':
      // do something else when view added...
      break;
  }
})
```

Actually, the issue is well expressed when we want to test the 'view_added' listener:
```
t.check('Listen to view_added event', {
    ignore: ignoreGlobal,
    init: async () => {
      const views = await mapx.ask('get_views');
      const view = views[0];
      await mapx.ask('open_view', {
        idView: view.id
      });
      return view;
    },
    tests: [
      {
        name: 'is triggered',
        test: async (r) => {
          var out = false;
          await mapx.on('view_added', view => {
            out = r.id == view.idView;
          });
          return out;
        }
      }
    ]
  });

```

**Comment by fxi** [comment] 2020-06-08 09:34
I don't get it. 

The test "listen to view_added event" is wrong ?

What do you mean by "the link btw the open and the opened event" ?

If you just need a proof that the view has been fully rendered, just wait : 
```js
console.log(`Before request`);
const added = await mapx.ask('open_view',{idView:'MX-4W6BQ-L2FVY-I24OR'});
console.log(`After request : view fully rendered = ${added} `)
```

And your suggestion will not work : the promise can only bu returned once. So, there will never be a `status === 'started'` and in a future point in time `status === 'finished'`. I think you mixed the web worker api or message api with promises api.

**Comment by fxi** [comment] 2020-06-08 10:14
What I can do is a callback in the config object : callbacks could be automatically linked to an event, internally.
```js
mapx.ask('view_add', {
  idView: 'abc',
  onAddStart : (v)=>{},
  onAddEnd : (v)=>{}
});
```
Or return an object with two promises to chain the logic 

```js
const res = mapx.ask('view_add', {idView: 'abc'});
/**
*{
*  onAdd: promise
*  onRendered : promise
* }
*/
res.onAddStart.then( v => ... )
res.onAddEnd.then( v => ... )
```
But this would mean breaking the "always returning a promise" idea.

**Comment by trepmag** [comment] 2020-06-08 12:43
Yes, or another alternative but might be more troublesome to implement:
```js
apx.ask('open_view', {idView: 'abc'}).then((r) =>
  console.log(r.object.id);
  // output 'abc'
  r.on('end', () => {
    // do something...
  });
});
```

But I dont want to add more work; perhaps `await mapx.ask('open_view',...});` is sufficient. Perhaps we can leave this resolver/listener chaining until we really find it is required; what do you thing?

**Comment by fxi** [comment] 2020-06-08 13:17
It's always easier to make fundamental change early in the project, that's why I asked to evaluate it thoroughly. Now, I have not much time left to implement all requested methods. If the chosen path does not fit your need, it's the very last time to make some change. Once it's in the wild, it's too late until V2.

**Comment by trepmag** [comment] 2020-06-08 13:46
Regarding this issue: if we want to sync this `open_view` resolver through its `view_added` listener then it's mostly welcome to have this adaptation otherwise we end with this kind of gymnastic I did: trepmag/map-x-mgl@1cd2964e536d7fbba0809203368ebbb35060dee5...

Then lets have this resolver/listener "chaining" now.

**Comment by fxi** [comment] 2020-06-08 13:53
Is that what does https://github.com/unep-grid/map-x-mgl/pull/552 ? I should merge it ?

By the way, there is no more 'open_view', everything is now 'view_add', 'view_remove', 'mx.helpers.viewAdd','mx.helpers.viewRemove', and events 'view_add', 'view_added', 'view_remove','view_removed' are kept.

**Comment by trepmag** [comment] 2020-06-08 14:44
#552 must not be merged; going to close! lets fix this issue when we have this chaining resolver/listener "chaining..."

**Comment by trepmag** [comment] 2020-07-03 08:59
Hello, as a follow up here is an example to chain started and finished events:
```js
class Manager {
  ask(method, arg) {
    return new Promise((resolveStarted) => {
      setTimeout(function() {
        let data = 'stuff...';
        let onFinished = new Promise((resolveFinished) => {
          setTimeout(function() {
            resolveFinished({
              method: method,
              arg: arg,
              status: 'finished',
              retult: data
            });
          }, 2000);
        });
        resolveStarted({
          method: method,
          arg: arg,
          status: 'started',
          result: data,
          onFinished: onFinished
        });
      }, 2000);
    });
  }
}

const m = new Manager();

console.log('Triggering getStuff...');
m.ask('getStuff', {id: 123}).then((item) => {
  console.log(item);
  return item.onFinished;
}).then((item) => {
  console.log(item);
});
```

**Closed** 2020-07-30 08:35 UTC
Labels: improvement, priority 2
