### ISSUE TITLE
Bug: the advanced filters do no work if the views have been organized by category

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#493] opened 2019-10-31 16:08 UTC
If the views have been organized by category **and** the category is collapsed, it is impossible to filter them, nothing appears in the view panel. The categories must be expanded to use the filter

![image](https://user-images.githubusercontent.com/25179050/67964557-c497e800-fc00-11e9-953e-839ae7969fb2.png)

![image](https://user-images.githubusercontent.com/25179050/67964593-d11c4080-fc00-11e9-9895-dd450bae0da4.png)

![image](https://user-images.githubusercontent.com/25179050/67964666-ec874b80-fc00-11e9-8a62-d52f1d6f781a.png)

![image](https://user-images.githubusercontent.com/25179050/67964716-00cb4880-fc01-11e9-9b1e-90e753e54e2f.png)

**Comment by fxi** [comment] 2019-11-04 14:49
@MarionPlanque  In filter mode, groups are ignored and some options are not available anymore. All views are visible in the first level of the view tree. Your second screenshot should contain some views, though. This could be a bug. If you suggest a complete workflow of what should be shown, which options are actionable for each situation, I can rebuild the logic. 

@thomaspiller @antobenve : Have you seen empty list after a filter event ?

**Comment by antobenve** [comment] 2019-11-04 14:58
@fxi, I confirm I had this issue as well when I reproduced @MarionPlanque 's suggestions.

**Comment by fxi** [comment] 2019-11-04 15:05
@antobenve  There are two issues here : 
1. Empty list despite a non-zero filter count. e.g. 20/60
2. The logic implemented aka "the flat mode"
If you had 1), did you keep some console log ? For 2), we have to discuss it.

**Comment by antobenve** [comment] 2019-11-04 15:17
Yes, I had empty list despite a non-zero filter count.
I was able to reproduce it now but nothing is received in the console.
![filter collections categories](https://user-images.githubusercontent.com/30286565/68132212-9a0a9f80-ff1e-11e9-994e-3bfe47ff19e9.gif)

**Comment by fxi** [comment] 2019-11-04 16:04
Ok, all groups are closed when the filter start, therefore their content not visible. I got it. I did not notice the closed group in the second screenshot.

**Comment by fxi** [comment] 2019-11-04 16:08
This is exactly what @MarionPlanque wrote in the first line of the issue description. Sorry. I should take more time to read issues.

**Comment by thomaspiller** [comment] 2019-11-05 15:32
Thanks for the fix. Unfortunately, the problem is partially solved as the implemented solution is not recursive. Views in nested categories are still hidden.

**Comment by fxi** [comment] 2019-11-20 08:27
Duplicate of #504. I close this one.

**Closed by fxi** 2019-11-20 08:27 UTC
Labels: bug, priority 2
