### ISSUE TITLE
SDK's manager ready event callback might not be applied when a reload is triggered

### ISSUE THREAD

**Issue by trepmag** [unep-grid/map-x-mgl#866] opened 2022-11-24 08:07 UTC
This happens when, for instance, mapx is pushing a new version and asking the user to reload. Then, it appears that on reload the initially `ready` callback isn't registered anymore or triggered on the reloaded instance?!...

**Comment by fxi** [comment] 2022-11-24 09:45
Thanks
It's maybe related to the `once` handler used here, preventing to re-register the whole thing. 
https://github.com/unep-grid/map-x-mgl/blob/staging/app/src/js/mx_helper_sdk.js#L10
If the window `load` event is not re-emitted after the reload... 
Will check this.
If it's urgent, I can try to solve this before the next release.

**Comment by fxi** [comment] 2023-01-17 09:50
As there is no reproducible example, I've made one : 

https://jsfiddle.net/fxi/6Loabz8k/

But I was not able to reproduce the behaviour. The 'ready' event is always received, even after a reload. 

Can you provide more info ?

**Comment by fxi** [comment] 2023-02-22 08:20
@trepmag Could you provide more info ?

**Comment by trepmag** [comment] 2023-02-22 08:43
Sorry not much since in practice reproducing the context isn't that much trivial (run a sdk app over a specific mapx version then rerun the same app over an update mapx version that requires a reload)...

**Comment by fxi** [comment] 2023-02-22 08:52
ok.. I see. We should probably do something to reload the page that holds the SDK manager, e.g. a message "updated" ? This would also make sure that the sdk package would be the latest version, if fetched from "app.mapx.org/sdk" ... If using a CDN, this could lead to some versions mismatch, though..

**Comment by fxi** [comment] 2023-02-22 10:05
I close this. After a dev session with @trepmag, I was able to test almost all cases of update in static/app mode and no issue observed.
However, if this issue is reproduced in a specific context, reopen it and add more information.
Thanks !

**Closed by fxi** 2023-02-22 10:05 UTC
Labels: bug, priority 1, wait feedback
