### ISSUE TITLE
Bug: the search fonction "filter views" is not applicable to views in *sub* categories

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#504] opened 2019-11-07 09:31 UTC
When views are aggregated in categories, they can be filtered, but when they are aggregated in sub-categories, they can not be filtered anymore.

Edit: same problem with "Filter activated views": it is only possible to see the views in categories, not in **sub** categories.

**Comment by thomaspiller** [comment] 2019-11-07 09:51
Duplicate of https://github.com/unep-grid/map-x-mgl/issues/493#issuecomment-549874704 ?

**Comment by MarionPlanque** [comment] 2019-11-07 10:03
No: bug 493 was about the filters applied to the categories
This one is about filter by "Search a view" in **sub** categories

**Comment by fxi** [comment] 2019-11-19 15:42
Seems to be working in version 1.6.31. Even is nested sub categories.

![mx_filter_sub](https://user-images.githubusercontent.com/1196833/69161089-e80ccf00-0aea-11ea-893f-b37d08b4e5da.gif)

**Comment by thomaspiller** [comment] 2019-12-16 09:26
This issue is solved in the online version.

**Closed by thomaspiller** 2019-12-16 09:26 UTC
Labels: bug, done
